server:
  port: 10204
  ssl:
    key-store: classpath:mycert.jks
    key-store-password: 123456
    key-store-type: JKS
spring:
  data:
    mongodb:
      host: 114.67.200.39
      port: 27817
      database: Hypertension
